Vagrant.configure("2") do |config|
  
  config.ssh.insert_key = false
  config.vm.provision :shell, path: "./shell/base.sh"

  config.vm.define "master", primary: true do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "kubernetes.master"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)"
    master.vm.provider "virtualbox" do |vb|
       vb.name = "kubernetes_master"
       vb.memory = "2048"
       vb.cpus = 2
    end
    # master.vm.provision :shell , path: "./shell/master.sh"
  end

  NodeCount = 2

  (1..NodeCount).each do |i|
    config.vm.define "slave#{i}" do |slave|
      slave.vm.box = "ubuntu/bionic64"
      slave.vm.hostname = "kubernetes.slave#{i}"
      slave.vm.network "private_network", ip: "192.168.33.1#{i}"
      slave.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)"
      slave.vm.provider "virtualbox" do |vb|
         vb.name = "kubernetes_slave#{i}"
         vb.memory = "1024"
         vb.cpus = 1
      end
      # slave.vm.provision :shell , path: "./shell/slave.sh"
    end
  end

end
