Vagrant.configure("2") do |config|

  config.vm.define "master", primary: true do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.provision :shell , path: "./shell/master.sh"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)"
    master.vm.provider "virtualbox" do |vb|
       vb.memory = "4096"
    end
  end

  config.vm.define "slave1" do |slave1|
    slave1.vm.box = "ubuntu/bionic64"
    slave1.vm.provision :shell , path: "./shell/slave1.sh"
    slave1.vm.network "private_network", ip: "192.168.33.11"
    slave1.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)"
    slave1.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
    end
  end
end
